### ISSUE TITLE
Addon not working since last update

### ISSUE THREAD

**Issue by HanaMobiyuki** [pereira-a/MBB#7]
Since last 4.0.7 update, the addon is breaking all the minimap section, I am not able to click the minimap buttons and the minimap isn't loading
Getting back to previous version is working

**Comment by uofirob** [comment]
I'm having this issue as well since update to 4.0.7

**Comment by CosmicCleric** [comment]
I'm the author of the 4.0.7 change. I'm not seeing that problem, could you elaborate on any error messages or further descriptions of how its not working, including what other addons you are using?

Have you tried a "/mbb reset all" (w/o the double quotes) ?

**Comment by pereira-a** [comment]
I think I found the root of the problem. It's conflicting with ElvUI addon. @HanaMobiyuki  @uofirob can you confirm that you use this addon?

**Comment by uofirob** [comment]
Yes I do use ELVUI

Message: Interface\AddOns\MBB\MBB.lua:624: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: MMHolder:SetPoint.
Time: Sat Jan 30 11:57:16 2021
Count: 6
Stack: Interface\AddOns\MBB\MBB.lua:624: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: MMHolder:SetPoint.
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:758: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "=[C]"]: in function `osetpoint'
[string "@Interface\AddOns\MBB\MBB.lua"]:624: in function `MBB_SetPositions'
[string "@Interface\AddOns\MBB\MBB.lua"]:751: in function `MBB_OnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: errMsg = "Interface\AddOns\MBB\MBB.lua:624: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: MMHolder:SetPoint."
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

**Comment by CosmicCleric** [comment]
FYI I don't use ELVUI.

Edit: /mbb buttons reports ...

MBB Buttons:
-  LibDBIcon10_DBM
- LibDBIcon10_DungeonTols
- LibDBIcon10_Details

BagSync button is not listed.

**Comment by pereira-a** [comment]
@CosmicCleric me neither. We will need to look at why considering "OnMouseUp" events conflicted with ElvUI. Also, why BagSync is missing from "/mbb button" output.

EDIT:
For now, I reverted the changes.

**Comment by CosmicCleric** [comment]
The only guess I have to the problem is that the change has the existing code examining/pulling in more buttons than it used to. It'll probably need some refactoring to handle the new stuff it pulls in, which is kind of weird since its just buttons/icons, it should just handle them all the same way really.

Sorry for the extra work on a Saturday!  :)

**Comment by pereira-a** [comment]
@CosmicCleric no problem at all. WoW has a large community and there are a lot of addons out there doing a lot of things and in different ways. It's impossible to test compatibility with all of them.

MBB has an old source code and maybe some things are not being done correctly, I need to be more careful in the future. 

Either way, you reported a bug (MBB is not recognizing some buttons) and again I thank you for that and for your contribution :) We just need to find another way to fix it.

**Comment by pereira-a** [comment]
A user of curseforge commented error logs on the project page related to this issue. This can help in the future:

`
29x MBB\MBB-4.0.4.lua:624: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: MMHolder:SetPoint.
[string "=[C]"]: in function `osetpoint'
[string "@MBB\MBB-4.0.4.lua"]:624: in function `MBB_SetPositions'
[string "@MBB\MBB-4.0.4.lua"]:751: in function `MBB_OnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
(*temporary) = MMHolder {
0 = <userdata>
ohide = <function> defined =[C]:-1
isvisible = true
SetHeight = <function> defined =[C]:-1
oclearallpoints = <function> defined =[C]:-1
SetSize = <function> defined =[C]:-1
SetPoint = <function> defined @MBB\MBB.lua:516
Hide = <function> defined @MBB\MBB.lua:402
ClearAllPoints = <function> defined @MBB\MBB.lua:514
parentisvisible = true
mover = MinimapMover {
}
Show = <function> defined @MBB\MBB.lua:385
SetWidth = <function> defined =[C]:-1
osize = <table> {
}
oshow = <function> defined =[C]:-1
osetpoint = <function> defined =[C]:-1
opoint = <table> {
}
}
(*temporary) = "RIGHT"
(*temporary) = MinimapPanel {
0 = <userdata>
isvisible = true
osetpoint = <function> defined =[C]:-1
OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:195
GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:433
anchor = "ANCHOR_BOTTOM"
TopLeftCorner = <unnamed> {
}
RightEdge = <unnamed> {
}
Hide = <function> defined @MBB\MBB.lua:402
template = "Default"
parentisvisible = true
ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:337
SetBackdrop = <function> defined @SharedXML\Backdrop.lua:372
dataPanels = <table> {
}
Show = <function> defined @MBB\MBB.lua:385
GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:452
GetBackdrop = <function> defined @SharedXML\Backdrop.lua:390
osize = <table> {
}
glossTex = true
SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:309
ohide = <function> defined =[C]:-1
PixelSnapDisabled = true
oclearallpoints = <function> defined =[C]:-1
oenter = <function> defined @ElvUI\Modules\DataTexts\DataTexts.lua:118
Center = <unnamed> {
}
opoint = <table> {
}
backdropInfo = <table> {
}
OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:225
HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:321
oleave = <function> defined @ElvUI\Modules\DataTexts\DataTexts.lua:135
SetPoint = <function> defined @MBB\MBB.lua:516
numPoints = 2
ClearAllPoints = <function> defined @MBB\MBB.lua:514
GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:231
ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:325
BottomEdge = <unnamed> {
}
TopEdge = <unnamed> {
}
BottomRightCorner = <unnamed> {
}
BottomLeftCorner = <unnamed> {
}
SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:257
yOff = -4
xOff = 0
oshow = <function> defined =[C]:-1
SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:465
SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:289
SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:442
LeftEdge = <unnamed> {
}
TopRightCorner = <unnamed> {
}
}
(*temporary) = "LEFT"
(*temporary) = 0
(*temporary) = 0
`

**Comment by CosmicCleric** [comment]
Quick follow-up question. Is the addon basically just detaching a child button from its parent frame and adding it to another parent frame, or is it reconstructing the child button from scratch?

**Comment by pereira-a** [comment]
I believe it is detaching and attaching.

**Comment by ItalianDragn** [comment]
Its breaking my ElvUI Minimap.  I just updated it at approximately 3PM PST 2020/1/30.
no other addons updated
I have to disable either the minimap in ElvUI or MinimapButtonBag otherwise my minimap is almost in the middle of the screen

**Comment by HanaMobiyuki** [comment]
Latest version 4.0.8 fixed my problem, thank you for you hard work on a saturday

**Comment by ItalianDragn** [comment]
> Latest version 4.0.8 fixed my problem, thank you for you hard work on a saturday

Ditto

**Comment by pereira-a** [comment]
For those who are interested in following up on the bug that version 4.0.7 tried to fix there's this issue: #6
